#! /usr/bin/env bash

export NATS_URL=nats://localhost:4222
export TEZOS_RPC_URI=http://localhost:20000
export WAREHOUSE_TEZOS_SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq  
export WAREHOUSE_CONTRACT_ADDRESS=KT1EWfDbL7PXzfbUog1zh2cDikc3fEvUhT48

function start() {
    node dist/index.js
}

function dev() {
    npm run dev
}

function build() {
    npm run build
}

"$@"