#! /usr/bin/env bash

export NATS_URL=nats://localhost:4222
export TEZOS_RPC_URI=http://localhost:20000
export WAREHOUSE_TEZOS_SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq  
export WAREHOUSE_TEZOS_PUBLIC_KEY_HASH=tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
# export WAREHOUSE_CONTRACT_ADDRESS=KT1BW8YPoG2hTFu3AXkQbgok9kYvhR1qbgL4

function start() {
    node dist/index.js
}

function dev() {
    npm run dev
}

function build() {
    npm run build
}

"$@"