version: 2.1
orbs:
    node: circleci/node@4.1.1
jobs:
    lint:
        executor: node/default
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: npm install
            - run: npx minilab start
            - run: sleep 180
            - run:
                  command: node ./mock-server/index.js
                  background: true
            - run: ./run build
            - run:
                  command: ./run start
                  background: true
            # wait for the contract to be deployed
            - run: sleep 60
            - run: JEST_TIMEOUT=60000 npm run test
workflows:
    tests:
        jobs:
            - lint
            - test
