version: 2.1
orbs:
    node: circleci/node@4.1.1
jobs:
    lint:
        executor: node/default
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
    test:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - run: npm install
            - run: npx minilab start
            - run: sleep 10
            - run: ./run build
            - run:
                command: ./run start
                background: true
            # wait for the contract to be deployed
            - run: sleep 20
            - run: npm run test
workflows:
    tests:
        jobs:
            - lint
            - test